### ISSUE TITLE
Training code in sample_flow

### ISSUE THREAD

**Issue by smethnani** [klightz/PSF#3]
I'm trying to understand the training code in sample_flow.py. I notice there is another break command [here](https://github.com/klightz/PSF/blob/8c334aaae09d1a53c6cc49f131530e9d3451a5aa/sample_flow.py#L578), does this not cause the code to only consider the first batch? What's the purpose of `noises_batch` (it's not used)? 

What's the purpose of the if command [here](https://github.com/klightz/PSF/blob/8c334aaae09d1a53c6cc49f131530e9d3451a5aa/sample_flow.py#L581)?

Is there an issue with the indentation [here](https://github.com/klightz/PSF/blob/8c334aaae09d1a53c6cc49f131530e9d3451a5aa/sample_flow.py#L599)? Will this cause torch.save to overwrite the sample pairs every epoch?

Are we supposed to [exit](https://github.com/klightz/PSF/blob/8c334aaae09d1a53c6cc49f131530e9d3451a5aa/sample_flow.py#L601) the process after the first epoch?

**Comment by klightz** [comment]
Hi, as for the break, it essentially means that we only need to generate a sample, bypassing the prior lines. Regarding the indentation for torch.save, in practice, you could adjust the save and exit one indent outwards to facilitate 200 iterations. In this code, to ensure seamless operation, I've opted to exit after the first round. I will consider revising these aspects to minimize confusion. Thank you for highlighting this.

**Comment by smethnani** [comment]
Okay I understand, thanks!
