### ISSUE TITLE
Issue in reflow training 

### ISSUE THREAD

**Issue by smethnani** [klightz/PSF#4]
HI, the following is the output of running `test_flow.py` with a trained flow model and step set to 20:
<img src='https://github.com/klightz/PSF/assets/82812166/b55c4e94-5a01-4665-9a62-8ed8b33cb81e' width='500'>

After fine tuning the flow model with `train_reflow.py`. The output of test_flow with the same number of steps:
<img src='https://github.com/klightz/PSF/assets/82812166/09d92b71-6c54-4591-85b9-c5b7ab5b7b3a' width='500'>

The samples should be improved with rectified flow or is this the expected output? Thanks.

**Comment by klightz** [comment]
Hi, ideally reflow will greatly improve the sample quality with 10-20 steps setup. There are several things need to be checked for the reflow step. 

1. How many samples are you sampled in sample_flow stage? Too few samples may lead a bad result, and we need to use 1000 steps to sample these pairs to ensure a good quality.

2. Reflow step is a refinement so typically fewer steps can get a good result, too much fine-tune steps may hurt the performance. 200 epochs is enough if we get a good quality sample pairs dataset.

**Comment by klightz** [comment]
Another thing is that could you briefly check your sample pair to see if x0 is noise and x1 is the samples shape? I find there are some messed order of x1 and x0 during my previous code merge. If you find x0 is not the noise, just flip them during the reflow. Sorry for the inconvenient.

**Comment by smethnani** [comment]
Hey thanks for the response. I used the default 200 steps for sample_flow and fine-tuned the model to epoch 200.

Vizualizing the sample pairs, I can see that they are indeed flipped. Thanks for the help! I'll rerun the reflow stage and try again.
