### ISSUE TITLE
Model sampler in sample_flow.py

### ISSUE THREAD

**Issue by smethnani** [klightz/PSF#5]
Should the model be using the trained flow model and ode sampler to generate the x1 of the pairs? The code appears to use the diffusion sampler. Is this a mistake or do I misunderstand the intended method or code? Thanks!

**Comment by klightz** [comment]
Hi, the code is still under cleaning but we do use ode style to sample pairs. You can find it [Here](https://github.com/klightz/PSF/blob/main/sample_flow.py#L118) . You may also use RK45 to speed up sampling, we give an implementation [Here](https://github.com/klightz/PSF/blob/main/test_flow.py#L36) .

**Comment by smethnani** [comment]
Thanks for clarifying.
