### ISSUE TITLE
Request answers to some doubts about running the code process

### ISSUE THREAD

**Issue by wangxin-fighting** [klightz/PSF#6]
Hello, excuse me. I would like to ask you a few questions.

First question: Running Python train_ When flow.py -- category car | chair | airplane, do I need to choose one of the car | chair | airplane options? Because I see in the code that one of the options is selected, rather than selecting all three at the same time.

Second question: train_ Flow.py, sample_ Flow.py, train_ Reflow. py, train_ Do I need to finish running the previous program before running the next program for these four programs?

Finally, may I ask if the train code needs to run 20000epoch, 10000epoch, 10000epoch, and 10000epoch respectively? I am running at a particularly slow speed, so I would like to ask if it is necessary to run so many epochs?

Looking forward to your reply and wishing you success in your work!

**Comment by klightz** [comment]
Thanks for being interested in our project.

 For the first question, by default, you can choose one or just leave it blank. You can also make it a list to train all the classed in the list.

Second, yes, they are depend on the previous checkpoint so you need to run them one by one.

Final question, no, you can run it for a shorter epochs, for example 500-1000, I remember it is enough to see some reasonable results. 20000 is just for marching other works and getting a best number during evaluation.

**Comment by wangxin-fighting** [comment]
Hello, after running 100epoch, I will generate the epoch_ Add 99.pth to sample_ When running 'parser. add_argument (' -- model ', default='./output/train_flow/2023-08-28-08-01-24/epoch_99. pth ', help=' path to model (to continue training) 'in flow.py, an error occurred as follows: What is the reason for this?


(wxpy38) wangxin@wangxin-IdeaCentre-GeekPro-17IAB:~/1_code/cvpr2023_PSF$ python sample_flow.py
Directory missing : ./data/ShapeNetCore.v2.PC15k/02691156/train
Traceback (most recent call last):
  File "sample_flow.py", line 699, in <module>
    main()
  File "sample_flow.py", line 618, in main
    train_dataset, _ = get_dataset(opt.dataroot, opt.npoints, opt.category)
  File "sample_flow.py", line 420, in get_dataset
    tr_dataset = ShapeNet15kPointClouds(root_dir=dataroot,
  File "/home/wangxin/1_code/cvpr2023_PSF/datasets/shapenet_data_pc.py", line 250, in __init__
    super(ShapeNet15kPointClouds, self).__init__(
  File "/home/wangxin/1_code/cvpr2023_PSF/datasets/shapenet_data_pc.py", line 100, in __init__
    self.all_points = np.concatenate(self.all_points)  # (N, 15000, 3)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate

**Comment by wangxin-fighting** [comment]
Hello, thank you for your enthusiastic answer earlier. After running the program 'train_flow. py' to the 99th epoch, my program stopped due to 'out of memory' and generated the weight 'epoch_99. pth'. Then, I added 'epoch_99. pth' to 'sample_flow. py' to train and run the program, but the following error occurred: What is the reason for this?

(wxpy38) wangxin@wangxin-IdeaCentre-GeekPro-17IAB:~/1_code/cvpr2023_PSF$ python sample_flow.py
Directory missing : ./data/ShapeNetCore.v2.PC15k/02691156/train
Traceback (most recent call last):
File "sample_flow.py", line 699, in
main()
File "sample_flow.py", line 618, in main
train_dataset, _ = get_dataset(opt.dataroot, opt.npoints, opt.category)
File "sample_flow.py", line 420, in get_dataset
tr_dataset = ShapeNet15kPointClouds(root_dir=dataroot,
File "/home/wangxin/1_code/cvpr2023_PSF/datasets/shapenet_data_pc.py", line 250, in init
super(ShapeNet15kPointClouds, self).init(
File "/home/wangxin/1_code/cvpr2023_PSF/datasets/shapenet_data_pc.py", line 100, in init
self.all_points = np.concatenate(self.all_points) # (N, 15000, 3)
File "<array_function internals>", line 200, in concatenate
ValueError: need at least one array to concatenate

**Comment by klightz** [comment]
Hi, I think this mainly because the data directory is set in a wrong way. Like the error message said: Directory missing : ./data/ShapeNetCore.v2.PC15k/02691156/train

in fact, sample step does not need a data input, but I reuse some of the code, so please at least set a valid dataset directory( maybe same as train_flow) then it should be ok.

**Comment by wangxin-fighting** [comment]
I initially forgot to change the location of the dataset, but after correcting the dataset path in 'sample_flow. py', I still reported the same error as before. Can you guide me?



(wxpy38) wangxin@wangxin-IdeaCentre-GeekPro-17IAB:~/1_code/cvpr2023_PSF$ python sample_flow.py
Directory missing : ./datasets/ShapeNetCore.v2.PC15k/ShapeNetCore.v2.PC15k/02691156/train
Traceback (most recent call last):
  File "sample_flow.py", line 699, in <module>
    main()
  File "sample_flow.py", line 618, in main
    train_dataset, _ = get_dataset(opt.dataroot, opt.npoints, opt.category)
  File "sample_flow.py", line 420, in get_dataset
    tr_dataset = ShapeNet15kPointClouds(root_dir=dataroot,
  File "/home/wangxin/1_code/cvpr2023_PSF/datasets/shapenet_data_pc.py", line 250, in __init__
    super(ShapeNet15kPointClouds, self).__init__(
  File "/home/wangxin/1_code/cvpr2023_PSF/datasets/shapenet_data_pc.py", line 100, in __init__
    self.all_points = np.concatenate(self.all_points)  # (N, 15000, 3)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate

**Comment by klightz** [comment]
I still see the error message 

Directory missing : ./datasets/ShapeNetCore.v2.PC15k/ShapeNetCore.v2.PC15k/02691156/train.

could you have a double check for this directory?
